[build]
target = "wasm32-unknown-unknown"
rustflags = ["--cfg", "getrandom_backend=\"wasm_js\""]

[test]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
runner = 'wasm-bindgen-test-runner'
